---
- name: Gestion de TestVM (Arrêt / Démarrage)
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: "MYRESOURCEGROUP"
    vm_name: "TestVM"
    action: "start"   # ou "stop"

  tasks:
    - name: Contrôler l'état de la VM
      azure.azcollection.azure_rm_virtualmachine_action:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        action: "{{ action }}"
