---
- name: Gestion de TestVM (Démarrage / Arrêt)
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: "MYRESOURCEGROUP"
    vm_name: "TestVM"
    vm_power_state: "start"   # "start" pour démarrer, "deallocate" pour arrêter

  tasks:
    - name: Contrôler l'état de la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        power_state: "{{ vm_power_state }}"
