---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MYRESOURCEGROUP_FR
    location: francecentral
    vm_name: NouvelleVM01
    vm_size: Standard_B1s
    admin_username: azureuser
    admin_password: "Ismael123!"  
    virtual_network: MyVNet
    subnet_name: MySubnet
    network_interface: MyNIC
    public_ip_name: MyPublicIP

  tasks:

  - name: Créer un groupe de ressources si inexistant
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Créer un réseau virtuel
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtual_network }}"
      address_prefixes: "10.0.0.0/16"
      dns_servers: []

  - name: Créer un subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.0.0/24"
      virtual_network: "{{ virtual_network }}"

  - name: Créer une IP publique Standard
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      name: "{{ public_ip_name }}"
      allocation_method: Static
      sku: Standard

  - name: Créer une NIC
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ network_interface }}"
      virtual_network: "{{ virtual_network }}"
      subnet: "{{ subnet_name }}"
      public_ip_name: "{{ public_ip_name }}"

  - name: Créer la VM Ubuntu
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      network_interface_names:
        - "{{ network_interface }}"
      image:
        offer: "0001-com-ubuntu-server-jammy"
        publisher: "Canonical"
        sku: "22_04-lts-gen2"
        version: latest
      os_type: Linux
      state: present
