---
- name: Provisionner VM Ubuntu avec IP publique Standard sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Créer l'IP publique Standard
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "MYRESOURCEGROUP"
        name: "NouvelleVM02-PIP"
        location: "francecentral"
        allocation_method: Static
        sku: Standard

    - name: Créer la NIC avec l'IP publique
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "MYRESOURCEGROUP"
        name: "NouvelleVM02-NIC"
        location: "francecentral"
        virtual_network: "VNet-MYRG"
        subnet: "Subnet-MYRG"
        public_ip_name: "NouvelleVM02-PIP"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "MYRESOURCEGROUP"
        name: "NouvelleVM02"
        location: "francecentral"
        vm_size: "Standard_B1s"
        admin_username: "azureuser"
        admin_password: "Ismael123!"
        image:
          offer: "0001-com-ubuntu-server-jammy"
          publisher: "Canonical"
          sku: "22_04-lts-gen2"
          version: "latest"
        network_interface_names:
          - "NouvelleVM02-NIC"
        ssh_password_enabled: yes
        state: present

