- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: "MYRESOURCEGROUP"
    vm_name: "NewTestVM"
    location: "East US"
    vm_size: "Standard_B1s"
    admin_username: "azureuser"
    admin_password: "Ismael123!"
    image:
      offer: "UbuntuServer"
      publisher: "Canonical"
      sku: "22.04-LTS"
      version: "latest"
  tasks:
    - name: Créer la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image:
          offer: "{{ image.offer }}"
          publisher: "{{ image.publisher }}"
          sku: "{{ image.sku }}"
          version: "{{ image.version }}"
        location: "{{ location }}"
        state: present
