---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MYRESOURCEGROUP_FR   
    location: francecentral               
    vm_name: NouvelleVM01                 
    vm_size: Standard_B1s                  
    admin_username: azureuser
    admin_password: "Ismael123!"
    vnet_name: MyVNet
    subnet_name: MySubnet
    ip_name: MyPublicIP
    nic_name: MyNIC
    image:
      offer: 0001-com-ubuntu-server-jammy
      publisher: Canonical
      sku: 22_04-lts-gen2
      version: latest

  tasks:
    - name: Créer le réseau virtuel si inexistant
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"
        state: present

    - name: Créer le subnet si inexistant
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ vnet_name }}"
        state: present

    - name: Créer une IP publique Standard
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        sku: Standard
        name: "{{ ip_name }}"
        location: "{{ location }}"
        state: present

    - name: Créer la NIC attachée à l'IP publique
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic_name }}"
        location: "{{ location }}"
        ip_configurations:
          - name: ipconfig1
            subnet: "{{ subnet_name }}"
            virtual_network: "{{ vnet_name }}"
            public_ip_address_name: "{{ ip_name }}"
        state: present

    - name: Créer la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interface_names:
          - "{{ nic_name }}"
        image:
          offer: "{{ image.offer }}"
          publisher: "{{ image.publisher }}"
          sku: "{{ image.sku }}"
          version: "{{ image.version }}"
        os_type: Linux
        state: present
