---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Créer la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: MYRESOURCEGROUP_FR
        name: NouvelleVM01
        vm_size: Standard_B1s
        admin_username: azureuser
        admin_password: Ismael123!
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: 22_04-lts-gen2
          version: latest
        location: francecentral
        network_interface_names: MyNIC01
        ssh_password_enabled: yes
