---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: "MYRESOURCEGROUP"
    location: "francecentral"
    virtual_network: "MyVNet"
    subnet_name: "MySubnet"
    network_interface: "MyNIC"
    public_ip_name: "MyPublicIP"
    vm_name: "NouvelleVM01"
    vm_size: "Standard_B1s"
    admin_username: "azureuser"
    admin_password: "Ismael123!"
    image_publisher: "Canonical"
    image_offer: "0001-com-ubuntu-server-jammy"
    image_sku: "22_04-lts-gen2"
  tasks:

    - name: Vérifier le quota d'IP publiques Standard
      azure.azcollection.azure_rm_network_usage_facts:
        location: "{{ location }}"
      register: network_usage

    - name: Déterminer si on peut créer une IP publique Standard
      set_fact:
        can_create_public_ip: "{{ (network_usage.network_resources | selectattr('name','equalto','Public IP Addresses - Standard') | first).current_value < (network_usage.network_resources | selectattr('name','equalto','Public IP Addresses - Standard') | first).limit }}"

    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer le virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        address_prefixes: "10.0.0.0/16"

    - name: Créer le subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.0.0/24"
        virtual_network: "{{ virtual_network }}"

    - name: Créer l'IP publique Standard si le quota le permet
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        sku: Standard
        name: "{{ public_ip_name }}"
        location: "{{ location }}"
      when: can_create_public_ip

    - name: Créer la NIC
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ network_interface }}"
        virtual_network: "{{ virtual_network }}"
        subnet: "{{ subnet_name }}"
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: "{{ public_ip_name if can_create_public_ip else omit }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image:
          publisher: "{{ image_publisher }}"
          offer: "{{ image_offer }}"
          sku: "{{ image_sku }}"
          version: latest
        network_interfaces:
          - "{{ network_interface }}"
        location: "{{ location }}"
