---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MYRESOURCEGROUP_FR
    location: francecentral
    vnet_name: MyVNet
    subnet_name: MySubnet
    public_ip_name: MyPublicIP
    nic_name: MyNIC
    vm_name: NouvelleVM01
    vm_size: Standard_B1s
    admin_username: azureuser
    admin_password: Ismael123!  
    image:
      publisher: Canonical
      offer: 0001-com-ubuntu-server-jammy
      sku: 22_04-lts-gen2
      version: latest

  tasks:
    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer le réseau virtuel si inexistant
      azure.azcollection.azure_rm_virtualnetwork:
        name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"

    - name: Créer le subnet si inexistant
      azure.azcollection.azure_rm_subnet:
        name: "{{ subnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ vnet_name }}"

    - name: Créer l'IP publique Standard
      azure.azcollection.azure_rm_publicipaddress:
        name: "{{ public_ip_name }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        allocation_method: Static
        sku: Standard

    - name: Créer la NIC attachée à l'IP publique
      azure.azcollection.azure_rm_networkinterface:
        name: "{{ nic_name }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        ip_configurations:
          - name: ipconfig1
            subnet_name: "{{ subnet_name }}"
            virtual_network: "{{ vnet_name }}"
            public_ip_name: "{{ public_ip_name }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interface_names:
          - "{{ nic_name }}"
        image: "{{ image }}"
        state: present
        os_disk:
          name: "{{ vm_name }}-osdisk"
          caching: ReadWrite
          create_option: FromImage
