---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: "MYRESOURCEGROUP"    
    vm_name: "NouvelleVM"                 
    location: "eastus"                     
    vm_size: "Standard_B1s"               
    admin_username: "azureuser"
    admin_password: "Ismael123!"          
    image_publisher: "Canonical"
    image_offer: "UbuntuServer"
    image_sku: "22_04-lts-gen2"
  tasks:
    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image:
          publisher: "{{ image_publisher }}"
          offer: "{{ image_offer }}"
          sku: "{{ image_sku }}"
          version: "latest"
        state: present
