---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    azure_subscription_id: "caf8f202-8483-4835-914f-76f3929c6423"
    azure_client_id: "8d8a3ad1-45e3-4fbd-a3b2-927ec0957531"
    azure_secret: "Pnd8Q~LAlUBHDnMgHffepouDDHN58ihwpTlLmcks"
    azure_tenant: "bee93534-ed21-4737-9b99-32e13fba7e02"

    resource_group: "MYRESOURCEGROUP_NEW"
    location: "francecentral"

    vnet_name: "MyVNetNew"
    subnet_name: "MySubnetNew"
    public_ip_name: "MyPublicIPNew"
    nic_name: "MyNICNew"
    vm_name: "NouvelleVMUbuntu"

    vm_size: "Standard_B1s"
    admin_username: "azureuser"
    admin_password: "MotDePasseComplexe123!"

    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 22_04-lts
      version: latest

  tasks:
    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer le réseau virtuel si inexistant
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: Créer le subnet si inexistant
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.0.0/24"
        virtual_network: "{{ vnet_name }}"

    - name: Créer une IP publique Standard
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        sku: Standard
        name: "{{ public_ip_name }}"
        location: "{{ location }}"

    - name: Créer la NIC attachée à l'IP publique
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic_name }}"
        location: "{{ location }}"
        ip_configurations:
          - name: "ipconfig1"
            subnet: "{{ subnet_name }}"
            virtual_network: "{{ vnet_name }}"
            public_ip_address_name: "{{ public_ip_name }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        network_interface_names:
          - "{{ nic_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image: "{{ image }}"
        os_type: Linux
