---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: "MYRESOURCEGROUP"
    location: "francecentral"
    vm_name: "NouvelleVM01"
    admin_username: "azureuser"
    admin_password: "Ismael123!"
    vm_size: "Standard_B1s"  
    vnet_name: "MyVNet"
    subnet_name: "MySubnet"
    nic_name: "NouvelleVM01-NIC"
    public_ip_name: "NouvelleVM01-PIP"

  tasks:
    - name: Créer un groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer un réseau virtuel
      azure.azcollection.azure_rm_virtualnetwork:
        name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"

    - name: Créer un subnet
      azure.azcollection.azure_rm_subnet:
        name: "{{ subnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ vnet_name }}"

    - name: Créer une IP publique Standard
      azure.azcollection.azure_rm_publicipaddress:
        name: "{{ public_ip_name }}"
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        sku: Standard
        location: "{{ location }}"

    - name: Créer la NIC et l'associer à la IP publique
      azure.azcollection.azure_rm_networkinterface:
        name: "{{ nic_name }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        ip_configurations:
          - name: ipconfig1
            subnet: "{{ subnet_name }}"
            virtual_network: "{{ vnet_name }}"
            public_ip_address_name: "{{ public_ip_name }}"

    - name: Créer la VM Ubuntu 22.04 LTS
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interface_names:
          - "{{ nic_name }}"
        image:
          offer: "0001-com-ubuntu-server-jammy"
          publisher: "Canonical"
          sku: "22_04-lts-gen2"
          version: "latest"
        os_type: Linux
        ssh_password_enabled: true
