---
- name: Créer une nouvelle VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Créer la VM Ubuntu avec IP publique Standard
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "MYRESOURCEGROUP"
        name: "NouvelleVM02"
        location: "francecentral"
        vm_size: "Standard_B1s"
        admin_username: "azureuser"
        admin_password: "Ismael123!"
        image:
          offer: "0001-com-ubuntu-server-jammy"
          publisher: "Canonical"
          sku: "22_04-lts-gen2"
          version: "latest"
        network_interface_names:
          - "NouvelleVM02-NIC"
        virtual_network_name: "VNet-MYRG"
        subnet_name: "Subnet-MYRG"
        public_ip_allocation_method: "Static"
        public_ip_sku: "Standard"
        ssh_password_enabled: yes
        state: present
