---
- name: Installer htop sur les serveurs avec EPEL
  hosts: all
  become: true

  tasks:
    - name: Installer le dépôt EPEL
      yum:
        name: epel-release
        state: present

    - name: Installer htop via YUM
      yum:
        name: htop
        state: present

    - name: Vérifier la version installée de htop
      command: htop --version
      register: htop_version
      changed_when: false

    - name: Afficher la version de htop
      debug:
        msg: "{{ htop_version.stdout }}"


