---
- name: Installer MariaDB (MySQL compatible) sur serveurs Linux
  hosts: all
  become: true

  tasks:
    - name: Installer MariaDB server
      yum:
        name: mariadb-server
        state: present

    - name: Démarrer et activer le service MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Assurer que le port 3306 est ouvert dans le firewall (si firewall actif)
      firewalld:
        service: mysql
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_facts['os_family'] == "RedHat"



