---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les packages nécessaires
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter la clé Docker officielle
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le repo Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Installer Docker
      apt:
        name: docker-ce
        state: latest

    - name: Vérifier que Docker fonctionne
      command: docker --version
      register: docker_version

    - debug:
        msg: "{{ docker_version.stdout }}"
