---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: yes
  vars:
    docker_gpg_key: /usr/share/keyrings/docker-archive-keyring.gpg
    docker_repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les dépendances nécessaires pour Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter la clé GPG officielle de Docker
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o {{ docker_gpg_key }}
      args:
        executable: /bin/bash

    - name: Ajouter le dépôt Docker
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo }}"
        state: present
        filename: docker.list

    - name: Mettre à jour à nouveau la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: S'assurer que le service Docker est démarré et activé
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
