---
- name: Installer et configurer Nginx
  hosts: 131.145.119.221
  become: true
  gather_facts: true

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Activer et démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Vérifier que Nginx fonctionne
      uri:
        url: http://localhost
        return_content: yes
      register: nginx_page

    - name: Afficher le contenu de la page Nginx
      debug:
        msg: "{{ nginx_page.content | truncate(100) }}"
