---
- name: Test accès root
  hosts: all
  become: yes
  tasks:
    - name: Vérifier l’utilisateur courant
      command: whoami
      register: result

    - debug:
        msg: "Utilisateur courant: {{ result.stdout }}"
