- name: Installer Nginx
  hosts: all
  become: true
  tasks:
    - name: Installer le paquet nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Activer nginx au démarrage
      ansible.builtin.service:
        name: nginx
        enabled: true

    - name: Démarrer nginx
      ansible.builtin.service:
        name: nginx
        state: started

