---
- name: Installer Docker
  hosts: all
  become: yes     
  tasks:
    - name: Installer paquets nécessaires
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes
