---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: true
  vars:
    docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg

  tasks:
    - name: Supprimer les fichiers de lock APT
      file:
        path: "{{ item }}"
        state: absent
        force: yes
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend

    - name: Corriger l'état dpkg en cas de problèmes
      command: dpkg --configure -a
      ignore_errors: yes

    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les dépendances nécessaires pour Docker
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker stable
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Mettre à jour la liste des paquets après ajout du dépôt
      apt:
        update_cache: yes

    - name: Installer Docker
      apt:
        name: docker-ce
        state: latest

    - name: S'assurer que le service Docker est démarré et activé
      service:
        name: docker
        state: started
        enabled: yes
