---
- name: Installer MariaDB sur le serveur cible
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Installer MariaDB Server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Démarrer le service MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
