---
- name: Installer Docker sur VM Ubuntu 22.04
  hosts: all
  become: true
  tasks:

    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer les dépendances nécessaires pour Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Ajouter le dépôt Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker.list

    - name: Mettre à jour la liste des paquets après ajout du dépôt
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: S'assurer que Docker est lancé et activé
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
