---
- name: Installer MySQL sur le serveur cible
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Installer MySQL Server
      ansible.builtin.yum:
        name: mysql-server
        state: present

    - name: Démarrer le service MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
