---
- name: Installer et configurer Nginx sur Ubuntu
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Supprimer les fichiers lock APT
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/cache/apt/archives/lock
      become: yes

    - name: Réinitialiser dpkg si nécessaire
      command: dpkg --configure -a
      become: yes
      ignore_errors: yes

    - name: Mettre à jour le cache apt
      apt:
        update_cache: yes
      become: yes

    - name: Installer nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: Activer et démarrer nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
      become: yes

    - name: Déployer une page d'accueil personnalisée
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Bienvenue sur mon serveur Nginx 🚀</title></head>
          <body>
          <h1>Installation réussie avec Ansible 🎉</h1>
          <p>Serveur provisionné automatiquement par AWX.</p>
          </body>
          </html>
        mode: '0644'
      become: yes
