---
- name: Installer Docker sur VM Ubuntu
  hosts: 131.145.119.221
  become: true
  become_method: sudo
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les dépendances pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        force: yes

    - name: Ajouter la clé GPG officielle Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le repository Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Mettre à jour les paquets après ajout du repo Docker
      apt:
        update_cache: yes

    - name: Installer Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Démarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Vérifier la version Docker installée
      command: docker --version
      register: docker_version

    - debug:
        msg: "{{ docker_version.stdout }}"
