---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les dépendances nécessaires
      apt:
        name: 
          - curl
        state: present

    - name: Télécharger et exécuter le script officiel Docker
      shell: |
        curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        sh /tmp/get-docker.sh
      args:
        executable: /bin/bash

    - name: Ajouter l'utilisateur courant au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Activer et démarrer le service Docker
      systemd:
        name: docker
        enabled: yes
        state: started
