---
- name: Installer Nginx sur Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
