---
- name: Installer Nginx sur VM Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer le service Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Vérifier que Nginx fonctionne
      command: systemctl status nginx
      register: nginx_status
      ignore_errors: yes

    - name: Afficher le statut de Nginx
      debug:
        var: nginx_status.stdout_lines
