---
- name: Installer Docker et Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour la VM
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer les dépendances pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Installer Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Installer Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ajouter l'utilisateur au groupe Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
