---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: true
  tasks:

    - name: Supprimer les fichiers de lock APT
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/extended_states

    - name: Recréer le fichier extended_states
      file:
        path: /var/lib/apt/extended_states
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Forcer la configuration des paquets bloqués
      command: dpkg --configure -a

    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les dépendances pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le repository Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Mettre à jour la liste des paquets après ajout du repo
      apt:
        update_cache: yes

    - name: Installer Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: S'assurer que le service Docker est démarré et activé
      systemd:
        name: docker
        state: started
        enabled: true
