---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: true
  vars:
    ansible_apt_install_retries: 5
    ansible_apt_install_retry_interval: 10

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Installer les paquets nécessaires pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Installer Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Démarrer et activer Docker
      systemd:
        name: docker
        state: started
        enabled: yes
