- name: Configurer TestVM
  hosts: testvm
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Apache2
      apt:
        name: apache2
        state: present
