---
- name: Création d'une VM Ubuntu avec IP publique sur Azure (sans NSG)
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group: "MyTestRG"
    location: "uksouth"
    vm_name: "UbuntuVMPublic"
    vm_size: "Standard_D2s_v3"
    admin_username: "azureuser"
    admin_password: "Ismael123!"
    public_ip_name: "UbuntuVMPublic-ip"
    nic_name: "UbuntuVMPublic-nic"
    vnet_name: "vnet-uksouth"
    subnet_name: "snet-uksouth-1"

  tasks:
    - name: Créer l'IP publique
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Dynamic
        name: "{{ public_ip_name }}"
        location: "{{ location }}"

    - name: Créer la NIC avec IP publique
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic_name }}"
        location: "{{ location }}"
        virtual_network: "{{ vnet_name }}"
        subnet_name: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces:
          - "{{ nic_name }}"
        image:
          offer: "0001-com-ubuntu-server-jammy"
          publisher: "Canonical"
          sku: "22_04-lts-gen2"
          version: "latest"
