---
- name: Création d'une VM Ubuntu sur Azure sans NSG
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group: "MyTestRG"
    location: "uksouth"
    vm_name: "UbuntuVMNoNSG"
    vm_size: "Standard_D2s_v3"
    admin_username: "azureuser"
    admin_password: "Ismael123!"    
    ssh_public_key_file: "{{ playbook_dir }}/files/id_rsa_awx.pub"

  tasks:
    - name: Vérifier que la clé publique existe
      stat:
        path: "{{ ssh_public_key_file }}"
      register: key_file

    - name: Échouer si la clé publique est introuvable
      fail:
        msg: "Le fichier de clé publique {{ ssh_public_key_file }} est introuvable."
      when: not key_file.stat.exists

    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: true      
        admin_password: "{{ admin_password }}"
        os_disk_name: "{{ vm_name }}-osdisk"
        managed_disk_type: Standard_LRS
        network_interface_names:
          - "{{ vm_name }}-nic"
        ssh_public_keys:
          - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', ssh_public_key_file) }}"
        image:
          publisher: "Canonical"
          offer: "0001-com-ubuntu-server-jammy"
          sku: "22_04-lts-gen2"
          version: "latest"

    - name: Créer une interface réseau pour la VM
      azure.azcollection.azure_rm_networkinterface:
        name: "{{ vm_name }}-nic"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        virtual_network: "vnet-{{ location }}"
        subnet: "snet-{{ location }}"
        public_ip_name: "{{ vm_name }}-publicip"
        enable_ip_forwarding: false
