---
- name: Création d'une VM Ubuntu sans NSG ni IP publique sur Azure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group: "MyTestRG"
    location: "uksouth"
    vm_name: "UbuntuVMNoPublicIP2"
    vm_size: "Standard_D2s_v3"
    admin_username: "azureuser"
    admin_password: "Ismael123!"
    virtual_network: "vnet-uksouth"
    subnet_name: "snet-uksouth-1"

  tasks:
    - name: Créer la VM Ubuntu avec NIC automatique
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image:
          publisher: "Canonical"
          offer: "0001-com-ubuntu-server-jammy"
          sku: "22_04-lts-gen2"
          version: "latest"
        os_disk_name: "{{ vm_name }}-osdisk"
        managed_disk_type: "Standard_LRS"
        ssh_password_enabled: true
        virtual_network_name: "{{ virtual_network }}"
        subnet_name: "{{ subnet_name }}"
        public_ip_allocation_method: Disabled
