---
- name: Création d'une VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group: "MyTestRG2"
    location: "uksouth"
    vm_name: "MyUbuntuVM2"
    vm_size: "Standard_D2s_v3"
    admin_username: "azureuser"
    admin_password: "Ismael123!"
    nsg_name: "MyNSG2"
    public_ip_name: "MyPublicIP2"
    nic_name: "MyNIC2"
    vnet_name: "vnet-uksouth"
    subnet_name: "snet-uksouth-1"

  tasks:

    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer le NSG
      azure.azcollection.azure_rm_networksecuritygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ nsg_name }}"
        location: "{{ location }}"
        security_rules:
          - name: AllowSSH
            priority: 1000
            direction: Inbound
            access: Allow
            protocol: Tcp
            source_address_prefix: "*"
            destination_port_range: 22

    - name: Créer l'adresse IP publique
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
        location: "{{ location }}"

    - name: Créer la NIC
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic_name }}"
        location: "{{ location }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"
        network_security_group: "{{ nsg_name }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        ssh_password_enabled: true
        network_interface_names:
          - "{{ nic_name }}"
        image:
          publisher: "Canonical"
          offer: "0001-com-ubuntu-server-jammy"
          sku: "22_04-lts-gen2"
          version: "latest"
