---
- name: Création d'une VM Debian/Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MyTestRG
    location: francecentral  
    vm_name: MyTestVM
    vm_size: Standard_B1s
    admin_username: azureuser
    awx_public_key_file: "{{ playbook_dir }}/files/id_rsa_awx.pub"
    image_publisher: Debian        
    image_offer: debian-11         
    image_sku: 11                

  tasks:
    - name: Vérifier que la clé publique existe
      stat:
        path: "{{ awx_public_key_file }}"
      register: pubkey

    - name: Échouer si la clé publique est introuvable
      fail:
        msg: "Le fichier de clé publique {{ awx_public_key_file }} est introuvable. Veuillez le créer."
      when: not pubkey.stat.exists

    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', awx_public_key_file) }}"
        image:
          publisher: "{{ image_publisher }}"
          offer: "{{ image_offer }}"
          sku: "{{ image_sku }}"
          version: latest
