---
- name: Créer une VM Ubuntu sur Azure avec SSH
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - azure.azcollection

  vars:
    resource_group: "MyTestRG"
    location: "francecentral"
    vm_name: "MyUbuntuVM"
    vm_size: "Standard_B1s"
    admin_username: "azureuser"
    ssh_pub_key_path: "/root/.ssh/awx_id_rsa.pub" 

  tasks:
    - name: Créer la VM Ubuntu avec clé SSH
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_public_keys:
          - "{{ lookup('file', ssh_pub_key_path) }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 22_04-lts
          version: latest
        state: present
