---
- name: Créer une VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    azure_resource_group: "MyTestRG"
    azure_location: "EastUS"           # à adapter selon ton besoin
    azure_vm_name: "MyUbuntuVM"
    azure_vm_size: "Standard_B1s"      # à adapter selon ton besoin
    azure_admin_user: "azureuser"
    ssh_public_key_path: "/var/lib/awx/ssh_keys/id_rsa_awx.pub"

  tasks:
    - name: Créer le groupe de ressources si inexistant
      azure_rm_resourcegroup:
        name: "{{ azure_resource_group }}"
        location: "{{ azure_location }}"

    - name: Créer la VM Ubuntu avec clé SSH
      azure_rm_virtualmachine:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_vm_name }}"
        vm_size: "{{ azure_vm_size }}"
        admin_username: "{{ azure_admin_user }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ azure_admin_user }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', ssh_public_key_path) }}"
        image:
          offer: "UbuntuServer"
          publisher: "Canonical"
          sku: "20_04-lts"
          version: "latest"
        state: present
      register: vm_creation

    - name: Afficher les infos de la VM
      debug:
        var: vm_creation
