---
- name: Créer une VM Ubuntu sur Azure avec SSH
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Créer la VM Ubuntu avec clé SSH
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: MyTestRG           
        name: MyUbuntuVM                   
        location: francecentral           
        vm_size: Standard_B1s               
        admin_username: azureuser          
        ssh_public_keys:
          - "{{ lookup('file', '/var/lib/awx/.ssh/id_rsa_awx.pub') }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 22_04-lts-gen2
          version: latest
