---
- name: Ajouter la clé publique AWX sur les serveurs distants
  hosts: all
  become: true
  vars:
    awx_public_key_file: "{{ playbook_dir }}/files/id_rsa_awx.pub"

  tasks:
    - name: Vérifier si la clé publique existe localement
      ansible.builtin.stat:
        path: "{{ awx_public_key_file }}"
      register: pubkey_stat
      delegate_to: localhost

    - name: Échouer si la clé publique est introuvable
      ansible.builtin.fail:
        msg: "Le fichier de clé publique {{ awx_public_key_file }} est introuvable. Veuillez le créer."
      when: not pubkey_stat.stat.exists

    - name: Lire la clé publique
      ansible.builtin.slurp:
        src: "{{ awx_public_key_file }}"
      register: pubkey_content
      delegate_to: localhost

    - name: Ajouter la clé publique dans authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ ansible_user | default('root') }}"
        key: "{{ pubkey_content.content | b64decode }}"
        state: present
