---
- name: Supprimer MyUbuntuVM et ses ressources associées
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: "MyTestRG"
    vm_name: "MyUbuntuVM"

  tasks:
    - name: Supprimer la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        state: absent

    - name: Supprimer le disque OS managé
      azure.azcollection.azure_rm_manageddisk:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}_OsDisk_1_f280046fe21b4781bd91fa238476ee09"
        state: absent

    - name: Supprimer l'interface réseau
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}VMNic"
        state: absent

    - name: Supprimer l'IP publique
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}PublicIP"
        state: absent

