---
- name: Créer une VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Créer la VM avec clé SSH
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: MyTestRG
        name: MyUbuntuVM
        vm_size: Standard_B1s
        admin_username: azureuser
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 22_04-lts
          version: latest
        ssh_public_keys:
          - "{{ lookup('file', '/tmp/awx_ssh/id_rsa_awx.pub') }}"
        state: present
