---
- name: Créer une VM Ubuntu sur Azure avec SSH
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - azure.azcollection

  vars:
    resource_group: "MyTestRG"        
    vm_name: "MyUbuntuVM"            
    location: "francecentral"        
    vm_size: "Standard_B1s"          
    admin_username: "ismael"         
    ssh_pub_key_path: "/home/ismael/.ssh/id_rsa.pub"  

  tasks:
    - name: Créer la VM Ubuntu avec clé SSH
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_public_keys:
          - path: /home/ismael/.ssh/authorized_keys
            key_data: "{{ lookup('file', ssh_pub_key_path) }}"
        image:
          offer: "0001-com-ubuntu-server-jammy"
          publisher: "Canonical"
          sku: "22_04-lts-gen2"
          version: "latest"
        state: present
