---
- name: Supprimer une VM Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MyTestRG
    vm_name: MyUbuntuVM

  tasks:
    - name: Supprimer la VM si elle existe
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        state: absent
