---
- name: Créer une VM Ubuntu simple sur Azure
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  vars:
    resource_group: "MyTestRG"
    vm_name: "MyUbuntuVM"
    vm_location: "francecentral"
    admin_username: "ismael"
    admin_password: "{{ vm_admin_password }}" 
    vm_size: "Standard_B1s"
    image: "UbuntuLTS"

  tasks:
    - name: Créer la VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ vm_location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image: "{{ image }}"
        state: present
