---
- name: Créer une VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MyTestRG
    location: eastus
    vm_name: UbuntuVM
    admin_username: azureuser
    ssh_public_key_path: /tmp/awx_ssh/id_rsa_awx.pub
    vm_size: Standard_B1s
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 22.04-LTS
      version: latest

  tasks:
    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', ssh_public_key_path) }}"
        image:
          offer: "{{ image.offer }}"
          publisher: "{{ image.publisher }}"
          sku: "{{ image.sku }}"
          version: "{{ image.version }}"
        state: present
        location: "{{ location }}"
