---
- name: Création d'une VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    azure_resource_group: "MyTestRG"
    azure_location: "francecentral"
    azure_vm_name: "MyUbuntuVM"
    azure_vm_size: "Standard_B1s"
    azure_admin_user: "azureuser"
    awx_public_key_file: "{{ playbook_dir }}/files/id_rsa_awx.pub"

  tasks:
    - name: Vérifier que la clé publique existe
      stat:
        path: "{{ awx_public_key_file }}"
      register: pubkey_file

    - name: Échouer si la clé publique est introuvable
      fail:
        msg: "Le fichier de clé publique {{ awx_public_key_file }} est introuvable."
      when: not pubkey_file.stat.exists

    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ azure_resource_group }}"
        location: "{{ azure_location }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ azure_vm_name }}"
        vm_size: "{{ azure_vm_size }}"
        admin_username: "{{ azure_admin_user }}"
        ssh_public_keys:
          - path: "/home/{{ azure_admin_user }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', awx_public_key_file) }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 22_04-lts-gen2
          version: latest
        state: present
