---
- name: Création d'une VM Ubuntu sur Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    resource_group: MyTestRG
    vm_name: MyUbuntuVM
    location: westeurope
    vm_size: Standard_B1s
    admin_username: azureuser
    ssh_public_key_file: "{{ playbook_dir }}/files/id_rsa_awx.pub"

  tasks:
    - name: Vérifier que la clé publique existe
      stat:
        path: "{{ ssh_public_key_file }}"
      register: ssh_key

    - name: Échouer si la clé publique est introuvable
      fail:
        msg: "Le fichier de clé publique {{ ssh_public_key_file }} est introuvable. Veuillez le créer."
      when: not ssh_key.stat.exists

    - name: Créer le groupe de ressources si inexistant
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Créer la VM Ubuntu
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: no
        ssh_public_keys:
          - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', ssh_public_key_file) }}"
        image:
          publisher: Canonical
          offer: UbuntuServer
          sku: 22_04-lts
          version: latest
        location: "{{ location }}"
