---
- name: Déployer nginx sur TestVM Azure
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
