---
- name: Installer Docker sur VM Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Démarrer et activer Docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
