---
- name: Vérifier les caractéristiques système de la VM
  hosts: azure_vms
  gather_facts: yes

  tasks:
    - name: Afficher les informations CPU
      debug:
        msg: "{{ ansible_processor }}"

    - name: Afficher la mémoire totale
      debug:
        msg: "{{ ansible_memtotal_mb }} MB"

    - name: Afficher la version de l’OS
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Afficher la taille des disques
      debug:
        msg: "{{ ansible_devices }}"

