---
- name: Mettre à jour les paquets sur VM Ubuntu
  hosts: 131.145.119.221
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
